apiVersion: 1

datasources:
  - name: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    version: 812
    jsonData:
      sslmode: disable
      timeField: "@timestamp"
      logMessageField: "line"

  - name: postgres
    type: postgres
    uid: postgres_ds
    isDefault: true
    url: postgres:5432
    database: logs_db
    user: user
    secureJsonData:
      password: pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
