{
 "title": "Issues Dashboard",
 "tags": [
  "postgres",
  "issues"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Events Distribution",
   "type": "piechart",
   "description": "Distribution of events from logs that are in Postgres",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'Tracebacks' AS label, COUNT(*) AS value FROM error_traceback\nUNION ALL\nSELECT 'Warnings' AS label, COUNT(*) AS value FROM events WHERE type = 'warning'\nUNION ALL\nSELECT 'Errors' AS label, COUNT(*) AS value FROM events WHERE type = 'error'\n"
    }
   ]
  },
  {
   "title": "Issues Status",
   "type": "barchart",
   "description": "Distribution of events from logs that are in Postgres",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 'Issues Open' AS label, COUNT(*) AS value FROM issues WHERE status = 'open'\nUNION ALL\nSELECT 'Issues Closed' AS label, COUNT(*) AS value FROM issues WHERE status = 'closed'\n"
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total FROM issues;"
    }
   ]
  },
  {
   "title": "Warnings Found",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total FROM events WHERE type = 'warning';\n"
    }
   ]
  },
  {
   "title": "Open Issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total FROM issues WHERE status = 'open';"
    }
   ]
  },
  {
   "title": "Closed Issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total FROM issues WHERE status = 'closed';"
    }
   ]
  },
  {
   "title": "Latest  Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT id, category, message, timestamp FROM issues WHERE status = 'open' ORDER BY id DESC;"
    }
   ]
  },
  {
   "title": "Errors traceback",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT \n    e.issue_id,\n    et.message,\n    et.line_number,\n    et.error_id,\n    et.hash,\n    et.id\nFROM error_traceback et\nJOIN events e ON et.error_id = e.id;\n"
    }
   ]
  },
  {
   "title": "Warnings Found",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT id, category, message, timestamp FROM events WHERE type = 'warning' ORDER BY id DESC;"
    }
   ]
  }
 ]
}